# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 465855b0ff7e54fa31bd57e098bc326fbe1bb15cf6957ffdaf8e8743dc5638d085db243ad912efa0ed1103990bfae6d21c8a0ef1bbebac6f18d2b04dfbda9e18

test:
  secret_key_base: d709f9a509b63a871a7897755de1aa262c335d9c959679128eb3831d66535f190fc87036730fec14ffe37a5e6d7252bf0df92bca4f2be7f112c5d13a8dff163c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
